territory_data = {
    "title": "4. Topographisches Grundwissen (Auswahl)",
    "gewässer": {
        "meere_meeresteile_und_seen": [
            "Pazifik (Pazifischer Ozean)",
            "Atlantik (Atlantischer Ozean)",
            "Indik (Indischer Ozean)",
            "Nordsee",
            "Ostsee",
            "Mittelmeer",
            "Rotes Meer",
            "Schwarzes Meer",
            "Großen Seen (Great Lakes)",
            "Victoriasee",
            "Baikalsee",
            "Kaspisches Meer",
            "Aralsee",
            "Totes Meer"
        ],
        "fluesse": [
            "Mississippi",
            "Missouri",
            "Amazonas",
            "Jangste (Chang Jiang)",
            "Gelber Fluss (Huang He)",
            "Ganges",
            "Indus",
            "Euphrat",
            "Tigris",
            "Donau",
            "Rhein",
            "Wolga",
            "Ob",
            "Jenissei",
            "Lena"
        ]
    },
    "inseln_inselgruppen": [
        "Neuguinea",
        "Borneo",
        "Sumatra",
        "Java",
        "Sri Lanka",
        "Philippinen",
        "Japan",
        "Neuseeland",
        "Madagaskar",
        "Kuba",
        "Grönland",
        "Island",
        "Britannien",
        "Irland",
        "Skandinavische Halbinsel",
        "Arabische Halbinsel",
        "Iberische Halbinsel",
        "Indochina",
        "Malakka"
    ],
    "gebirge": [
        "Rocky Mountains",
        "Anden",
        "Himalaya",
        "Hindukusch",
        "Pamir",
        "Kaukasus",
        "Ural",
        "Alpen",
        "Apennin",
        "Karpaten",
        "Pyrenäen",
        "Atlas",
        "Zentralmassiv"
    ]
}
